server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true
    username: root
    password: Rezolut@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

# This code is used for circuit breaker;

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

#here we also write code for Retry;

#  retry:
#    instances:
#      ratingHotelService2:
#        max-attempts: 3
#        wait-duration: 5s
#

#write the code for Rate limiter

#  ratelimiter:
#    instances:
#      userRateLimiter1:
#        limit-refresh-period: 4s
#        limit-for-period: 2
#        timeout-duration: 0s


